SELECT DISTINCT MOVIE_NAME
  FROM SCHEDULE S
INNER JOIN MOVIES M
   ON S.MOVIE_ID = M.MOVIE_ID 
ORDER BY MOVIE_NAME;



SELECT DISTINCT MOVIE_NAME
  FROM SCHEDULE
INNER JOIN MOVIES
   ON SCHEDULE.MOVIE_ID = MOVIES.MOVIE_ID 
ORDER BY MOVIE_NAME;